# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Flake8

on: [push, pull_request]

jobs:
  flake8:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
#    strategy:
#      matrix:
#        python-version: [3.6]
    env:
      python-version: 3.6
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Get pip cache dir
        id: pip-cache
        if: always()
        run: |
          python -m pip install --upgrade pip
          echo "::set-output name=dir::$(python -m pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        if: always()
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ env.python-version }}-pip-tests-${{ hashFiles('./requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.python-version }}-pip-tests
            ${{ runner.os }}-${{ env.python-version }}-pip
      - name: Setup Python environment
        if: always()
        run: |
          python -m venv "${HOME}/.venv"
          source "${HOME}/.venv/bin/activate"
          cd ./${GITHUB_REPOSITORY##*/}
          pip install --upgrade pip wheel setuptools
          if [ -f flake8_requirements.txt ]; then
              pip install -r flake8_requirements.txt | cat; test ${PIPESTATUS[0]} -eq 0
          else
              pip install flake8 | cat; test ${PIPESTATUS[0]} -eq 0
          fi
      - name: Run Flake8
        env:
          $FLAKE8_WARNINGS: ${{ secrets.FLAKE8_WARNINGS }}
        run: |
          cd ./${GITHUB_REPOSITORY##*/}
          source "${HOME}/.venv/bin/activate"
          flake8
